const p = '/assets/images/naman_brands';

export const liveCampaigns = [
  {
    brand: "Beardo",
    brandLogo: `${p}/beardo.jpg`,
    role: "Grooming Content Creators for New Launch",
    badge: "Hiring Now",
    budget: "₹15K–30K",
    fit: "Men's grooming, lifestyle, or fitness creators. Authentic product demos preferred. Engagement-first.",
    niche: "Men's Grooming",
    location: "Pan India",
    timeline: "2 weeks",
    deliverables: ["2 Reels", "3 Stories", "1 Carousel"],
    theme: { primary: "#1a1a1a", primaryDeep: "#000000", accentText: "#1a1a1a", cardBorder: "rgba(0,0,0,0.12)", badgeColor: "#1a1a1a", liveIndicator: "#1a1a1a" },
  },
  {
    brand: "OPPO India",
    brandLogo: `${p}/oppoindia.jpg`,
    role: "Tech Reviewers — Flagship Launch Push",
    badge: "Urgent",
    budget: "₹20K–45K",
    fit: "Smartphone & tech gadget reviewers. Engaged urban audience that responds to CTA-driven posts.",
    niche: "Tech / Gadgets",
    location: "Metro Cities",
    timeline: "10 days",
    deliverables: ["1 Long Reel", "2 Stories", "1 Post"],
    theme: { primary: "#3a3a3a", primaryDeep: "#1a1a1a", accentText: "#2d2d2d", cardBorder: "rgba(50,50,50,0.15)", badgeColor: "#2d2d2d", liveIndicator: "#3a3a3a" },
  },
  {
    brand: "Tira Beauty",
    brandLogo: `${p}/tirabeauty.jpg`,
    role: "Beauty & Skincare Ambassadors",
    badge: "Open",
    budget: "₹10K–22K",
    fit: "Beauty, skincare, or lifestyle creators with an authentic, minimal aesthetic. Brand alignment over follower count.",
    niche: "Beauty / Skincare",
    location: "All India",
    timeline: "3 weeks",
    deliverables: ["2 Reels", "1 Blog Post", "2 Stories"],
    theme: { primary: "#e63312", primaryDeep: "#cc2a0e", accentText: "#c42710", cardBorder: "rgba(230,51,18,0.16)", badgeColor: "#c42710", liveIndicator: "#e63312" },
  },
  {
    brand: "Amazon Music",
    brandLogo: `${p}/amazon_music.jpg`,
    role: "Music & Lifestyle Content Creators",
    badge: "Hiring Now",
    budget: "₹25K–50K",
    fit: "Music enthusiasts, playlist curators, or lifestyle creators. Strong audio-visual content skills required.",
    niche: "Music / Entertainment",
    location: "Pan India",
    timeline: "2 weeks",
    deliverables: ["2 Reels", "1 Story Series", "1 Post"],
    theme: { primary: "#25d1da", primaryDeep: "#1ab8c0", accentText: "#0e9da5", cardBorder: "rgba(37,209,218,0.18)", badgeColor: "#0e9da5", liveIndicator: "#25d1da" },
  },
  {
    brand: "Aqualogica",
    brandLogo: `${p}/aqualogica.jpg`,
    role: "Skincare Routine Creators",
    badge: "Open",
    budget: "₹12K–28K",
    fit: "Skincare, derma-beauty creators. Clean, aesthetic content style. Focus on hydration and routine content.",
    niche: "Skincare / Beauty",
    location: "Tier 1 & 2 Cities",
    timeline: "3 weeks",
    deliverables: ["2 Reels", "3 Stories", "1 Carousel"],
    theme: { primary: "#0e7490", primaryDeep: "#0c5f75", accentText: "#0c5f75", cardBorder: "rgba(14,116,144,0.18)", badgeColor: "#0c5f75", liveIndicator: "#0e7490" },
  },
  {
    brand: "Adventure Hive",
    brandLogo: `${p}/adventurehive.jpg`,
    role: "Travel & Outdoor Adventure Creators",
    badge: "Open",
    budget: "₹8K–18K",
    fit: "Travel, trekking, or outdoor adventure creators. Authentic storytelling with scenic visuals.",
    niche: "Travel / Adventure",
    location: "All India",
    timeline: "4 weeks",
    deliverables: ["1 Reel", "2 Stories", "1 Post"],
    theme: { primary: "#b45309", primaryDeep: "#92400e", accentText: "#92400e", cardBorder: "rgba(180,83,9,0.18)", badgeColor: "#92400e", liveIndicator: "#b45309" },
  },
  {
    brand: "Director Special",
    brandLogo: `${p}/director_special_ilaichi.jpg`,
    role: "Premium Lifestyle Brand Ambassadors",
    badge: "Hiring Now",
    budget: "₹18K–35K",
    fit: "Premium lifestyle, food, or wellness creators. Elegant content style with sophisticated audience.",
    niche: "Lifestyle / Premium",
    location: "Metro Cities",
    timeline: "2 weeks",
    deliverables: ["2 Reels", "1 Story", "1 Post"],
    theme: { primary: "#b8860b", primaryDeep: "#996f0a", accentText: "#8b7300", cardBorder: "rgba(184,134,11,0.18)", badgeColor: "#8b7300", liveIndicator: "#b8860b" },
  },
  {
    brand: "Eno",
    brandLogo: `${p}/eno.jpg`,
    role: "Health & Wellness Creators",
    badge: "Urgent",
    budget: "₹15K–30K",
    fit: "Health, food, or lifestyle creators. Relatable everyday scenarios. Mass appeal audience.",
    niche: "Health / FMCG",
    location: "Pan India",
    timeline: "10 days",
    deliverables: ["2 Reels", "3 Stories"],
    theme: { primary: "#4d7c0f", primaryDeep: "#3f6212", accentText: "#3f6212", cardBorder: "rgba(77,124,15,0.18)", badgeColor: "#3f6212", liveIndicator: "#4d7c0f" },
  },
  {
    brand: "Farmley",
    brandLogo: `${p}/farmly.jpg`,
    role: "Healthy Snacking Content Creators",
    badge: "Open",
    budget: "₹10K–20K",
    fit: "Food, fitness, or health-conscious creators. Farm-to-table messaging, organic lifestyle content.",
    niche: "Food / Health",
    location: "All India",
    timeline: "3 weeks",
    deliverables: ["2 Reels", "2 Stories", "1 Post"],
    theme: { primary: "#eab308", primaryDeep: "#ca8a04", accentText: "#854d0e", cardBorder: "rgba(234,179,8,0.18)", badgeColor: "#854d0e", liveIndicator: "#eab308" },
  },
  {
    brand: "Flipkart Reset",
    brandLogo: `${p}/flipcartresetindia.jpg`,
    role: "E-Commerce Deal Hunters",
    badge: "Hiring Now",
    budget: "₹20K–40K",
    fit: "Tech, deals, or lifestyle creators. High engagement with product reviews and unboxing content.",
    niche: "E-Commerce / Tech",
    location: "Pan India",
    timeline: "1 week",
    deliverables: ["1 Long Reel", "2 Stories", "1 Post"],
    theme: { primary: "#2563eb", primaryDeep: "#1d4ed8", accentText: "#1d4ed8", cardBorder: "rgba(37,99,235,0.18)", badgeColor: "#1d4ed8", liveIndicator: "#2563eb" },
  },
  {
    brand: "Floweraura",
    brandLogo: `${p}/floweraura.jpg`,
    role: "Gifting & Occasions Creators",
    badge: "Open",
    budget: "₹8K–16K",
    fit: "Lifestyle, gifting, or relationship content creators. Romantic and festive storytelling.",
    niche: "Gifting / Lifestyle",
    location: "All India",
    timeline: "3 weeks",
    deliverables: ["2 Reels", "2 Stories"],
    theme: { primary: "#0d6e7e", primaryDeep: "#0a5b68", accentText: "#0a5b68", cardBorder: "rgba(13,110,126,0.18)", badgeColor: "#0a5b68", liveIndicator: "#0d6e7e" },
  },
  {
    brand: "Gillette India",
    brandLogo: `${p}/gilletindia.jpg`,
    role: "Men's Grooming Campaign Creators",
    badge: "Urgent",
    budget: "₹22K–45K",
    fit: "Men's grooming, fitness, or lifestyle creators. Premium feel with strong male demographic.",
    niche: "Men's Grooming",
    location: "Metro Cities",
    timeline: "10 days",
    deliverables: ["2 Reels", "3 Stories", "1 Post"],
    theme: { primary: "#1e3a6e", primaryDeep: "#162d55", accentText: "#162d55", cardBorder: "rgba(30,58,110,0.18)", badgeColor: "#162d55", liveIndicator: "#1e3a6e" },
  },
  {
    brand: "Heer by GIVA",
    brandLogo: `${p}/heerbygiva.jpg`,
    role: "Luxury Jewellery Ambassadors",
    badge: "Open",
    budget: "₹12K–25K",
    fit: "Fashion, jewellery, or luxury lifestyle creators. Aspirational content with elegant aesthetics.",
    niche: "Jewellery / Fashion",
    location: "All India",
    timeline: "3 weeks",
    deliverables: ["2 Reels", "1 Blog Post", "2 Stories"],
    theme: { primary: "#6b9e8a", primaryDeep: "#4d8570", accentText: "#2d5e4a", cardBorder: "rgba(107,158,138,0.18)", badgeColor: "#2d5e4a", liveIndicator: "#6b9e8a" },
  },
  {
    brand: "Lakmé Salon",
    brandLogo: `${p}/lakmesalon.jpg`,
    role: "Beauty & Salon Experience Creators",
    badge: "Hiring Now",
    budget: "₹18K–35K",
    fit: "Beauty, makeup, or salon content creators. Professional beauty services and transformation content.",
    niche: "Beauty / Salon",
    location: "Metro Cities",
    timeline: "2 weeks",
    deliverables: ["2 Reels", "3 Stories", "1 Carousel"],
    theme: { primary: "#1a1a1a", primaryDeep: "#000000", accentText: "#1a1a1a", cardBorder: "rgba(0,0,0,0.12)", badgeColor: "#1a1a1a", liveIndicator: "#b8860b" },
  },
  {
    brand: "Nippon India MF",
    brandLogo: `${p}/nippon_investable.jpg`,
    role: "Finance & Investment Creators",
    badge: "Open",
    budget: "₹15K–30K",
    fit: "Finance, investment, or money management creators. Educational content style preferred.",
    niche: "Finance / Fintech",
    location: "Pan India",
    timeline: "3 weeks",
    deliverables: ["1 Long Reel", "2 Stories", "1 Post"],
    theme: { primary: "#dc2626", primaryDeep: "#b91c1c", accentText: "#991b1b", cardBorder: "rgba(220,38,38,0.16)", badgeColor: "#991b1b", liveIndicator: "#dc2626" },
  },
  {
    brand: "Pepero",
    brandLogo: `${p}/pepro.jpg`,
    role: "Snack & Food Content Creators",
    badge: "Urgent",
    budget: "₹10K–22K",
    fit: "Food, snacking, or daily lifestyle creators. Fun, relatable content with youth appeal.",
    niche: "Food / Snacks",
    location: "All India",
    timeline: "10 days",
    deliverables: ["2 Reels", "2 Stories", "1 Post"],
    theme: { primary: "#c81e1e", primaryDeep: "#a51c1c", accentText: "#991b1b", cardBorder: "rgba(200,30,30,0.16)", badgeColor: "#991b1b", liveIndicator: "#c81e1e" },
  },
  {
    brand: "Real Juice",
    brandLogo: `${p}/realjuice.jpg`,
    role: "Healthy Beverage Creators",
    badge: "Open",
    budget: "₹8K–18K",
    fit: "Health, food, or family lifestyle creators. Natural juice benefits and healthy living content.",
    niche: "Beverages / Health",
    location: "Pan India",
    timeline: "3 weeks",
    deliverables: ["2 Reels", "3 Stories"],
    theme: { primary: "#1d4ed8", primaryDeep: "#1e40af", accentText: "#1e3a8a", cardBorder: "rgba(29,78,216,0.16)", badgeColor: "#1e3a8a", liveIndicator: "#1d4ed8" },
  },
  {
    brand: "Saffola",
    brandLogo: `${p}/saffola_foodie.jpg`,
    role: "Healthy Cooking Content Creators",
    badge: "Hiring Now",
    budget: "₹12K–25K",
    fit: "Cooking, food, or health-conscious creators. Nutritional focus with family-friendly recipes.",
    niche: "Food / Cooking",
    location: "All India",
    timeline: "2 weeks",
    deliverables: ["2 Reels", "2 Stories", "1 Carousel"],
    theme: { primary: "#b91c1c", primaryDeep: "#991b1b", accentText: "#7f1d1d", cardBorder: "rgba(185,28,28,0.16)", badgeColor: "#7f1d1d", liveIndicator: "#b91c1c" },
  },
  {
    brand: "Jupiter App",
    brandLogo: `${p}/thejupiterapp.jpg`,
    role: "Fintech & Money Management Creators",
    badge: "Urgent",
    budget: "₹15K–32K",
    fit: "Finance, fintech, or young professional creators. Digital banking and savings content.",
    niche: "Fintech / Finance",
    location: "Metro Cities",
    timeline: "10 days",
    deliverables: ["1 Reel", "2 Stories", "1 Post"],
    theme: { primary: "#ef6461", primaryDeep: "#e04542", accentText: "#c93a37", cardBorder: "rgba(239,100,97,0.18)", badgeColor: "#c93a37", liveIndicator: "#ef6461" },
  },
];
